GET http://localhost:5234/games

###
GET http://localhost:5234/games/1

###
POST http://localhost:5234/games
Content-Type: application/json

{
    "name": "Minecraft22",
    "genreId": 5,
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5234/games/1
Content-Type: application/json

{
    "name": "Counter Strike 2",
    "genreId": 2,
    "price": 15.99,
    "releaseDate": "2023-09-15"
}

###
DELETE http://localhost:5234/games/1